name: Make luci-app-quickstart RunFile

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号，如0.9.7-1'
        required: true
        default: '0.9.7-1'
      download_url:
        description: '完整IPK下载链接'
        required: true
        default: 'https://dl.openwrt.ai/releases/24.10/packages/x86_64/kiddin9/luci-app-quickstart_0.11.1-r1-r12_all.ipk'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y curl makeself

      - name: 创建目录
        run: mkdir -p build/x86_64

      - name: 下载IPK
        run: |
          curl -fLo build/x86_64/luci-app-quickstart_${{ github.event.inputs.version }}_x86_64.ipk "${{ github.event.inputs.download_url }}"

      - name: 生成安装脚本
        run: |
          echo '#!/bin/sh' > build/x86_64/install.sh
          echo 'echo "更新软件源..."' >> build/x86_64/install.sh
          echo 'opkg update || exit 1' >> build/x86_64/install.sh
          echo 'echo "安装 luci-app-quickstart..."' >> build/x86_64/install.sh
          echo 'opkg install luci-app-quickstart_*.ipk || exit 1' >> build/x86_64/install.sh
          echo 'echo "安装完成"' >> build/x86_64/install.sh
          chmod +x build/x86_64/install.sh

      - name: 制作 .run 文件
        run: |
          git clone https://github.com/megastep/makeself.git
          mv build/x86_64 makeself/
          cd makeself
          ./makeself.sh x86_64 luci-app-quickstart-${{ github.event.inputs.version }}-x86_64.run "luci-app-quickstart 安装器" ./install.sh
          cd ..

      - name: 上传 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "quickstart-${{ github.event.inputs.version }}"
          name: "luci-app-quickstart-${{ github.event.inputs.version }}"
          files: makeself/luci-app-quickstart-${{ github.event.inputs.version }}-x86_64.run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
